### PR TITLE
Resolve conflict between tf and cl headers

### LINKED ISSUE #26: `Content-Length` header conflicts with `Transfer-Encoding`
Vert.x server adds `Transfer-Encoding: chunked` header to every response. However by HTTP standards it should not be done if `Content-Length` header presents in response. Some HTTP clients fail to handle responses from Vert.x server due to violation of this rule. We should not add `Transfer-Encoding: chunked` header if `Content-Length` header is already there.

### PR DESCRIPTION
**Pull request by Sammers21**
Closes #26

### CODE REVIEW

File: src/main/java/com/artipie/vertx/VertxConnection.java [hunk 1]
```diff
@@ -62,13 +62,27 @@
...
+                .doOnError(promise::completeExceptionally)
+                .forEach(this.rsp::write);
+        } else {
+            this.rsp.setChunked(true);
+            Flowable.fromPublisher(body)
+                .map(VertxConnection::mapBuffer)
+                .doOnComplete(() -> promise.complete(this.rsp))
+                .doOnError(promise::completeExceptionally)
+                .subscribe(this.rsp.toSubscriber());
+        }
```
Comment (olegmoz) [inline src/main/java/com/artipie/vertx/VertxConnection.java]: @Sammers21 I'd suggest to extract common code from these two branches, it would be:
```
Flowable.fromPublisher(body)
  .map(VertxConnection::mapBuffer)
  .doOnError(promise::completeExceptionally)
```

File: src/test/java/com/artipie/vertx/VertxSliceServerTest.java [hunk 2]
```diff
@@ -122,7 +122,7 @@ public void serverHandlesBasicRequest() {
 
     @Test
     public void basicGetRequest() {
-        final String expected = "Hello World!!!";
+        final String expected = "Hello World!!!!";
```
Comment (olegmoz) [inline src/test/java/com/artipie/vertx/VertxSliceServerTest.java]: @Sammers21 let's keep unrelated test intact, you may use different string constant in new test

File: src/test/java/com/artipie/vertx/VertxSliceServerTest.java [hunk 3]
```diff
@@ -139,6 +139,26 @@ public void basicGetRequest() {
...
+                    Integer.toString(expected.length())
+                ),
+                Flowable.fromArray(ByteBuffer.wrap(expected.getBytes()))
+            )
+        );
+        final String actual = this.client.get(this.port, VertxSliceServerTest.HOST, "/hello2")
+            .rxSend()
+            .blockingGet()
+            .bodyAsString();
+        MatcherAssert.assertThat(actual, Matchers.equalTo(expected));
```
Comment (olegmoz) [inline src/test/java/com/artipie/vertx/VertxSliceServerTest.java:165]: @Sammers21 the test should check that there is not `Transfer-Encoding` header in response, otherwise it does not really check the issue at hand

File: src/test/java/com/artipie/vertx/VertxSliceServerTest.java [hunk 4]
```diff
@@ -139,6 +139,26 @@ public void basicGetRequest() {
         MatcherAssert.assertThat(actual, Matchers.equalTo(expected));
     }
 
+    @Test
+    public void basicGetRequestCL() {
```
Comment (olegmoz) [inline src/test/java/com/artipie/vertx/VertxSliceServerTest.java]: @Sammers21 please improve test name, it should describe that we test delivery of response with `Content-Length` header. It is not clear what `CL` here means

**Review by olegmoz — CHANGES_REQUESTED** [review]
@Sammers21 thanks, please see the comments

**Comment by Sammers21** [comment]
@olegmoz, review the PR one more time, please.

File: src/test/java/com/artipie/vertx/VertxSliceServerTest.java (hunk 2 above)
Comment (olegmoz) [reply src/test/java/com/artipie/vertx/VertxSliceServerTest.java]: @Sammers21 please revert changes in this line and we are good to merge

**Review by olegmoz — CHANGES_REQUESTED** [review]
@Sammers21 thanks, please fix one problem and we are good to merge

**Comment by Sammers21** [comment]
@olegmoz, review the PR one more time, please.

**Review by olegmoz — APPROVED** [review]
@Sammers21 thanks, merging
